//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Iot.Daq.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Iot.Daq.Core.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Snet.cn ] Iot 轻量级数采 的本地化字符串。
        /// </summary>
        public static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebApi停止失败 的本地化字符串。
        /// </summary>
        public static string WebApi停止失败 {
            get {
                return ResourceManager.GetString("WebApi停止失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebApi停止成功 的本地化字符串。
        /// </summary>
        public static string WebApi停止成功 {
            get {
                return ResourceManager.GetString("WebApi停止成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebApi启动失败 的本地化字符串。
        /// </summary>
        public static string WebApi启动失败 {
            get {
                return ResourceManager.GetString("WebApi启动失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebApi启动成功 的本地化字符串。
        /// </summary>
        public static string WebApi启动成功 {
            get {
                return ResourceManager.GetString("WebApi启动成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传插件 的本地化字符串。
        /// </summary>
        public static string 上传插件 {
            get {
                return ResourceManager.GetString("上传插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载选中的插件 的本地化字符串。
        /// </summary>
        public static string 下载选中的插件 {
            get {
                return ResourceManager.GetString("下载选中的插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持类型转换 的本地化字符串。
        /// </summary>
        public static string 不支持类型转换 {
            get {
                return ResourceManager.GetString("不支持类型转换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个点位删除失败 的本地化字符串。
        /// </summary>
        public static string 个点位删除失败 {
            get {
                return ResourceManager.GetString("个点位删除失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个点位导入失败 的本地化字符串。
        /// </summary>
        public static string 个点位导入失败 {
            get {
                return ResourceManager.GetString("个点位导入失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为所有地址添加设备 的本地化字符串。
        /// </summary>
        public static string 为所有地址添加设备 {
            get {
                return ResourceManager.GetString("为所有地址添加设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string 主页 {
            get {
                return ResourceManager.GetString("主页", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输失败 的本地化字符串。
        /// </summary>
        public static string 传输失败 {
            get {
                return ResourceManager.GetString("传输失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输成功 的本地化字符串。
        /// </summary>
        public static string 传输成功 {
            get {
                return ResourceManager.GetString("传输成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 .net10 WPF 终端形式开发全流程配置采集与消息队列转发 的本地化字符串。
        /// </summary>
        public static string 使用__net10_WPF_终端形式开发全流程配置采集与消息队列转发 {
            get {
                return ResourceManager.GetString("使用 .net10 WPF 终端形式开发全流程配置采集与消息队列转发", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string 信息 {
            get {
                return ResourceManager.GetString("信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string 修改 {
            get {
                return ResourceManager.GetString("修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改WebApi 的本地化字符串。
        /// </summary>
        public static string 修改WebApi {
            get {
                return ResourceManager.GetString("修改WebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功 的本地化字符串。
        /// </summary>
        public static string 修改成功 {
            get {
                return ResourceManager.GetString("修改成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改插件配置 的本地化字符串。
        /// </summary>
        public static string 修改插件配置 {
            get {
                return ResourceManager.GetString("修改插件配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改自动组包 的本地化字符串。
        /// </summary>
        public static string 修改自动组包 {
            get {
                return ResourceManager.GetString("修改自动组包", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改设备配置 的本地化字符串。
        /// </summary>
        public static string 修改设备配置 {
            get {
                return ResourceManager.GetString("修改设备配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改项 的本地化字符串。
        /// </summary>
        public static string 修改项 {
            get {
                return ResourceManager.GetString("修改项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string 停止 {
            get {
                return ResourceManager.GetString("停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止下载插件 的本地化字符串。
        /// </summary>
        public static string 停止下载插件 {
            get {
                return ResourceManager.GetString("停止下载插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止采集 的本地化字符串。
        /// </summary>
        public static string 停止采集 {
            get {
                return ResourceManager.GetString("停止采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常捕获 的本地化字符串。
        /// </summary>
        public static string 全局异常捕获 {
            get {
                return ResourceManager.GetString("全局异常捕获", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string 全选 {
            get {
                return ResourceManager.GetString("全选", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string 关于 {
            get {
                return ResourceManager.GetString("关于", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        public static string 写入 {
            get {
                return ResourceManager.GetString("写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入失败 的本地化字符串。
        /// </summary>
        public static string 写入失败 {
            get {
                return ResourceManager.GetString("写入失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入成功 的本地化字符串。
        /// </summary>
        public static string 写入成功 {
            get {
                return ResourceManager.GetString("写入成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        public static string 列表 {
            get {
                return ResourceManager.GetString("列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string 删除成功 {
            get {
                return ResourceManager.GetString("删除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名 的本地化字符串。
        /// </summary>
        public static string 别名 {
            get {
                return ResourceManager.GetString("别名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string 刷新 {
            get {
                return ResourceManager.GetString("刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包名 的本地化字符串。
        /// </summary>
        public static string 包名 {
            get {
                return ResourceManager.GetString("包名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数设置 的本地化字符串。
        /// </summary>
        public static string 参数设置 {
            get {
                return ResourceManager.GetString("参数设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string 反选 {
            get {
                return ResourceManager.GetString("反选", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消软启采集 的本地化字符串。
        /// </summary>
        public static string 取消软启采集 {
            get {
                return ResourceManager.GetString("取消软启采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消软启采集成功 的本地化字符串。
        /// </summary>
        public static string 取消软启采集成功 {
            get {
                return ResourceManager.GetString("取消软启采集成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台设备已成功加载 的本地化字符串。
        /// </summary>
        public static string 台设备已成功加载 {
            get {
                return ResourceManager.GetString("台设备已成功加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string 启动 {
            get {
                return ResourceManager.GetString("启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动采集 的本地化字符串。
        /// </summary>
        public static string 启动采集 {
            get {
                return ResourceManager.GetString("启动采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唯一标识符 的本地化字符串。
        /// </summary>
        public static string 唯一标识符 {
            get {
                return ResourceManager.GetString("唯一标识符", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string 图标 {
            get {
                return ResourceManager.GetString("图标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string 地址 {
            get {
                return ResourceManager.GetString("地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址不能为空 的本地化字符串。
        /// </summary>
        public static string 地址不能为空 {
            get {
                return ResourceManager.GetString("地址不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址别名不能为空 的本地化字符串。
        /// </summary>
        public static string 地址别名不能为空 {
            get {
                return ResourceManager.GetString("地址别名不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址处理 的本地化字符串。
        /// </summary>
        public static string 地址处理 {
            get {
                return ResourceManager.GetString("地址处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址数量 的本地化字符串。
        /// </summary>
        public static string 地址数量 {
            get {
                return ResourceManager.GetString("地址数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址文件转换 的本地化字符串。
        /// </summary>
        public static string 地址文件转换 {
            get {
                return ResourceManager.GetString("地址文件转换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址设置 的本地化字符串。
        /// </summary>
        public static string 地址设置 {
            get {
                return ResourceManager.GetString("地址设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址配置在项目设置中有使用 的本地化字符串。
        /// </summary>
        public static string 地址配置在项目设置中有使用 {
            get {
                return ResourceManager.GetString("地址配置在项目设置中有使用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制JSON 的本地化字符串。
        /// </summary>
        public static string 复制JSON {
            get {
                return ResourceManager.GetString("复制JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制唯一标识符 的本地化字符串。
        /// </summary>
        public static string 复制唯一标识符 {
            get {
                return ResourceManager.GetString("复制唯一标识符", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string 失败 {
            get {
                return ResourceManager.GetString("失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节处理 的本地化字符串。
        /// </summary>
        public static string 字节处理 {
            get {
                return ResourceManager.GetString("字节处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在 的本地化字符串。
        /// </summary>
        public static string 存在 {
            get {
                return ResourceManager.GetString("存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在传输失败数据如下 的本地化字符串。
        /// </summary>
        public static string 存在传输失败数据如下 {
            get {
                return ResourceManager.GetString("存在传输失败数据如下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string 导入 {
            get {
                return ResourceManager.GetString("导入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入取消 的本地化字符串。
        /// </summary>
        public static string 导入取消 {
            get {
                return ResourceManager.GetString("导入取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败 的本地化字符串。
        /// </summary>
        public static string 导入失败 {
            get {
                return ResourceManager.GetString("导入失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        public static string 导入成功 {
            get {
                return ResourceManager.GetString("导入成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string 导出 {
            get {
                return ResourceManager.GetString("导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出失败 的本地化字符串。
        /// </summary>
        public static string 导出失败 {
            get {
                return ResourceManager.GetString("导出失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        public static string 导出成功 {
            get {
                return ResourceManager.GetString("导出成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开 的本地化字符串。
        /// </summary>
        public static string 展开 {
            get {
                return ResourceManager.GetString("展开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开所有 的本地化字符串。
        /// </summary>
        public static string 展开所有 {
            get {
                return ResourceManager.GetString("展开所有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止下载插件 的本地化字符串。
        /// </summary>
        public static string 已停止下载插件 {
            get {
                return ResourceManager.GetString("已停止下载插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启动 的本地化字符串。
        /// </summary>
        public static string 已启动 {
            get {
                return ResourceManager.GetString("已启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布尔位索引 的本地化字符串。
        /// </summary>
        public static string 布尔位索引 {
            get {
                return ResourceManager.GetString("布尔位索引", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string 序号 {
            get {
                return ResourceManager.GetString("序号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string 异常 {
            get {
                return ResourceManager.GetString("异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速搭建数据采集服务终端 的本地化字符串。
        /// </summary>
        public static string 快速搭建数据采集服务终端 {
            get {
                return ResourceManager.GetString("快速搭建数据采集服务终端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string 成功 {
            get {
                return ResourceManager.GetString("成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动添加一个地址 的本地化字符串。
        /// </summary>
        public static string 手动添加一个地址 {
            get {
                return ResourceManager.GetString("手动添加一个地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开插件存储路径 的本地化字符串。
        /// </summary>
        public static string 打开插件存储路径 {
            get {
                return ResourceManager.GetString("打开插件存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展参数不正确 的本地化字符串。
        /// </summary>
        public static string 扩展参数不正确 {
            get {
                return ResourceManager.GetString("扩展参数不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折叠 的本地化字符串。
        /// </summary>
        public static string 折叠 {
            get {
                return ResourceManager.GetString("折叠", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折叠所有 的本地化字符串。
        /// </summary>
        public static string 折叠所有 {
            get {
                return ResourceManager.GetString("折叠所有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制 的本地化字符串。
        /// </summary>
        public static string 控制 {
            get {
                return ResourceManager.GetString("控制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制台 的本地化字符串。
        /// </summary>
        public static string 控制台 {
            get {
                return ResourceManager.GetString("控制台", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string 描述 {
            get {
                return ResourceManager.GetString("描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件上传成功 的本地化字符串。
        /// </summary>
        public static string 插件上传成功 {
            get {
                return ResourceManager.GetString("插件上传成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件下载失败 的本地化字符串。
        /// </summary>
        public static string 插件下载失败 {
            get {
                return ResourceManager.GetString("插件下载失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件下载完成 的本地化字符串。
        /// </summary>
        public static string 插件下载完成 {
            get {
                return ResourceManager.GetString("插件下载完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件列表 的本地化字符串。
        /// </summary>
        public static string 插件列表 {
            get {
                return ResourceManager.GetString("插件列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件存储路径不存在 的本地化字符串。
        /// </summary>
        public static string 插件存储路径不存在 {
            get {
                return ResourceManager.GetString("插件存储路径不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件尚未加载 的本地化字符串。
        /// </summary>
        public static string 插件尚未加载 {
            get {
                return ResourceManager.GetString("插件尚未加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新完成 的本地化字符串。
        /// </summary>
        public static string 插件更新完成 {
            get {
                return ResourceManager.GetString("插件更新完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件浏览 的本地化字符串。
        /// </summary>
        public static string 插件浏览 {
            get {
                return ResourceManager.GetString("插件浏览", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件热更新成功 的本地化字符串。
        /// </summary>
        public static string 插件热更新成功 {
            get {
                return ResourceManager.GetString("插件热更新成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件版本 的本地化字符串。
        /// </summary>
        public static string 插件版本 {
            get {
                return ResourceManager.GetString("插件版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件移除成功 的本地化字符串。
        /// </summary>
        public static string 插件移除成功 {
            get {
                return ResourceManager.GetString("插件移除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件类型 的本地化字符串。
        /// </summary>
        public static string 插件类型 {
            get {
                return ResourceManager.GetString("插件类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件设置 的本地化字符串。
        /// </summary>
        public static string 插件设置 {
            get {
                return ResourceManager.GetString("插件设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件配置 的本地化字符串。
        /// </summary>
        public static string 插件配置 {
            get {
                return ResourceManager.GetString("插件配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string 搜索 {
            get {
                return ResourceManager.GetString("搜索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string 操作 {
            get {
                return ResourceManager.GetString("操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据格式 的本地化字符串。
        /// </summary>
        public static string 数据格式 {
            get {
                return ResourceManager.GetString("数据格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        public static string 数据类型 {
            get {
                return ResourceManager.GetString("数据类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件内容发生改变 的本地化字符串。
        /// </summary>
        public static string 文件内容发生改变 {
            get {
                return ResourceManager.GetString("文件内容发生改变", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示窗口 的本地化字符串。
        /// </summary>
        public static string 显示窗口 {
            get {
                return ResourceManager.GetString("显示窗口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新插件 的本地化字符串。
        /// </summary>
        public static string 更新插件 {
            get {
                return ResourceManager.GetString("更新插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        public static string 更新时间 {
            get {
                return ResourceManager.GetString("更新时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间 的本地化字符串。
        /// </summary>
        public static string 最后更新时间 {
            get {
                return ResourceManager.GetString("最后更新时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务停止 的本地化字符串。
        /// </summary>
        public static string 服务停止 {
            get {
                return ResourceManager.GetString("服务停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务启动 的本地化字符串。
        /// </summary>
        public static string 服务启动 {
            get {
                return ResourceManager.GetString("服务启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务数据修改 的本地化字符串。
        /// </summary>
        public static string 服务数据修改 {
            get {
                return ResourceManager.GetString("服务数据修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启动 的本地化字符串。
        /// </summary>
        public static string 未启动 {
            get {
                return ResourceManager.GetString("未启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未查询到对应内容 的本地化字符串。
        /// </summary>
        public static string 未查询到对应内容 {
            get {
                return ResourceManager.GetString("未查询到对应内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检索到对应项 的本地化字符串。
        /// </summary>
        public static string 未检索到对应项 {
            get {
                return ResourceManager.GetString("未检索到对应项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string 未知 {
            get {
                return ResourceManager.GetString("未知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置WebApi参数 的本地化字符串。
        /// </summary>
        public static string 未设置WebApi参数 {
            get {
                return ResourceManager.GetString("未设置WebApi参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string 查询 {
            get {
                return ResourceManager.GetString("查询", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string 正常 {
            get {
                return ResourceManager.GetString("正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此驱动目前不支持地址自动组包 的本地化字符串。
        /// </summary>
        public static string 此驱动目前不支持地址自动组包 {
            get {
                return ResourceManager.GetString("此驱动目前不支持地址自动组包", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string 添加 {
            get {
                return ResourceManager.GetString("添加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加地址 的本地化字符串。
        /// </summary>
        public static string 添加地址 {
            get {
                return ResourceManager.GetString("添加地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加插件配置 的本地化字符串。
        /// </summary>
        public static string 添加插件配置 {
            get {
                return ResourceManager.GetString("添加插件配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加时间 的本地化字符串。
        /// </summary>
        public static string 添加时间 {
            get {
                return ResourceManager.GetString("添加时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备 的本地化字符串。
        /// </summary>
        public static string 添加设备 {
            get {
                return ResourceManager.GetString("添加设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加软启采集 的本地化字符串。
        /// </summary>
        public static string 添加软启采集 {
            get {
                return ResourceManager.GetString("添加软启采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加软启采集成功 的本地化字符串。
        /// </summary>
        public static string 添加软启采集成功 {
            get {
                return ResourceManager.GetString("添加软启采集成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加顶级项 的本地化字符串。
        /// </summary>
        public static string 添加顶级项 {
            get {
                return ResourceManager.GetString("添加顶级项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项 的本地化字符串。
        /// </summary>
        public static string 添加项 {
            get {
                return ResourceManager.GetString("添加项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string 清空 {
            get {
                return ResourceManager.GetString("清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空插件存储路径 的本地化字符串。
        /// </summary>
        public static string 清空插件存储路径 {
            get {
                return ResourceManager.GetString("清空插件存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示 的本地化字符串。
        /// </summary>
        public static string 温馨提示 {
            get {
                return ResourceManager.GetString("温馨提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string 版本 {
            get {
                return ResourceManager.GetString("版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物联网插件化数据采集 的本地化字符串。
        /// </summary>
        public static string 物联网插件化数据采集 {
            get {
                return ResourceManager.GetString("物联网插件化数据采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物联网数轻量化数据采集 的本地化字符串。
        /// </summary>
        public static string 物联网数轻量化数据采集 {
            get {
                return ResourceManager.GetString("物联网数轻量化数据采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string 状态 {
            get {
                return ResourceManager.GetString("状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态验证 的本地化字符串。
        /// </summary>
        public static string 状态验证 {
            get {
                return ResourceManager.GetString("状态验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产 的本地化字符串。
        /// </summary>
        public static string 生产 {
            get {
                return ResourceManager.GetString("生产", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控 的本地化字符串。
        /// </summary>
        public static string 监控 {
            get {
                return ResourceManager.GetString("监控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string 移除 {
            get {
                return ResourceManager.GetString("移除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除WebApi 的本地化字符串。
        /// </summary>
        public static string 移除WebApi {
            get {
                return ResourceManager.GetString("移除WebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除成功 的本地化字符串。
        /// </summary>
        public static string 移除成功 {
            get {
                return ResourceManager.GetString("移除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除所有 的本地化字符串。
        /// </summary>
        public static string 移除所有 {
            get {
                return ResourceManager.GetString("移除所有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除插件 的本地化字符串。
        /// </summary>
        public static string 移除插件 {
            get {
                return ResourceManager.GetString("移除插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除插件配置 的本地化字符串。
        /// </summary>
        public static string 移除插件配置 {
            get {
                return ResourceManager.GetString("移除插件配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除自动组包 的本地化字符串。
        /// </summary>
        public static string 移除自动组包 {
            get {
                return ResourceManager.GetString("移除自动组包", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员运行 的本地化字符串。
        /// </summary>
        public static string 管理员运行 {
            get {
                return ResourceManager.GetString("管理员运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string 类型 {
            get {
                return ResourceManager.GetString("类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组包结果为空 的本地化字符串。
        /// </summary>
        public static string 组包结果为空 {
            get {
                return ResourceManager.GetString("组包结果为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        public static string 结果 {
            get {
                return ResourceManager.GetString("结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码类型 的本地化字符串。
        /// </summary>
        public static string 编码类型 {
            get {
                return ResourceManager.GetString("编码类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备层级 的本地化字符串。
        /// </summary>
        public static string 设备层级 {
            get {
                return ResourceManager.GetString("设备层级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        public static string 设备类型 {
            get {
                return ResourceManager.GetString("设备类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置WebApi 的本地化字符串。
        /// </summary>
        public static string 设置WebApi {
            get {
                return ResourceManager.GetString("设置WebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成功 的本地化字符串。
        /// </summary>
        public static string 设置成功 {
            get {
                return ResourceManager.GetString("设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置自动组包 的本地化字符串。
        /// </summary>
        public static string 设置自动组包 {
            get {
                return ResourceManager.GetString("设置自动组包", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该插件配置文件在项目设置中有使用 的本地化字符串。
        /// </summary>
        public static string 该插件配置文件在项目设置中有使用 {
            get {
                return ResourceManager.GetString("该插件配置文件在项目设置中有使用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string 详情 {
            get {
                return ResourceManager.GetString("详情", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先移除该插件的所有配置文件 的本地化字符串。
        /// </summary>
        public static string 请先移除该插件的所有配置文件 {
            get {
                return ResourceManager.GetString("请先移除该插件的所有配置文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择要下载的插件 的本地化字符串。
        /// </summary>
        public static string 请先选择要下载的插件 {
            get {
                return ResourceManager.GetString("请先选择要下载的插件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求示例 的本地化字符串。
        /// </summary>
        public static string 请求示例 {
            get {
                return ResourceManager.GetString("请求示例", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入地址名称 的本地化字符串。
        /// </summary>
        public static string 请输入地址名称 {
            get {
                return ResourceManager.GetString("请输入地址名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入描述 的本地化字符串。
        /// </summary>
        public static string 请输入描述 {
            get {
                return ResourceManager.GetString("请输入描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件 的本地化字符串。
        /// </summary>
        public static string 请选择文件 {
            get {
                return ResourceManager.GetString("请选择文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件夹 的本地化字符串。
        /// </summary>
        public static string 请选择文件夹 {
            get {
                return ResourceManager.GetString("请选择文件夹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        public static string 读取 {
            get {
                return ResourceManager.GetString("读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败 的本地化字符串。
        /// </summary>
        public static string 读取失败 {
            get {
                return ResourceManager.GetString("读取失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取成功 的本地化字符串。
        /// </summary>
        public static string 读取成功 {
            get {
                return ResourceManager.GetString("读取成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始位 的本地化字符串。
        /// </summary>
        public static string 起始位 {
            get {
                return ResourceManager.GetString("起始位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换失败 的本地化字符串。
        /// </summary>
        public static string 转换失败 {
            get {
                return ResourceManager.GetString("转换失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出选择 的本地化字符串。
        /// </summary>
        public static string 退出选择 {
            get {
                return ResourceManager.GetString("退出选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中 的本地化字符串。
        /// </summary>
        public static string 选中 {
            get {
                return ResourceManager.GetString("选中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选则插件存储路径 的本地化字符串。
        /// </summary>
        public static string 选则插件存储路径 {
            get {
                return ResourceManager.GetString("选则插件存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string 选择 {
            get {
                return ResourceManager.GetString("选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择选中项 的本地化字符串。
        /// </summary>
        public static string 选择选中项 {
            get {
                return ResourceManager.GetString("选择选中项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集 的本地化字符串。
        /// </summary>
        public static string 采集 {
            get {
                return ResourceManager.GetString("采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集失败 的本地化字符串。
        /// </summary>
        public static string 采集失败 {
            get {
                return ResourceManager.GetString("采集失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集时间 的本地化字符串。
        /// </summary>
        public static string 采集时间 {
            get {
                return ResourceManager.GetString("采集时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集状态 的本地化字符串。
        /// </summary>
        public static string 采集状态 {
            get {
                return ResourceManager.GetString("采集状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        public static string 重试 {
            get {
                return ResourceManager.GetString("重试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string 长度 {
            get {
                return ResourceManager.GetString("长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目列表 的本地化字符串。
        /// </summary>
        public static string 项目列表 {
            get {
                return ResourceManager.GetString("项目列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目设置 的本地化字符串。
        /// </summary>
        public static string 项目设置 {
            get {
                return ResourceManager.GetString("项目设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目详情 的本地化字符串。
        /// </summary>
        public static string 项目详情 {
            get {
                return ResourceManager.GetString("项目详情", resourceCulture);
            }
        }
    }
}
